// Regenerates cloud/src/lib/cloudFields.js from shared/data/syncRegistry.js
// (Cloud Phase 2 plan §6.1). Run from the repo root after changing the registry:
//   node cloud/scripts/cloud-fields.mjs > cloud/src/lib/cloudFields.js
// cloud/tests/cloudFields.test.js fails until you do.
import { cloudFieldManifest } from '../../shared/data/syncRegistry.js';

const body = JSON.stringify(cloudFieldManifest(), null, 2);
process.stdout.write(`// GENERATED by cloud/scripts/cloud-fields.mjs from shared/data/syncRegistry.js.
// Do not edit by hand: change the registry, then regenerate (Cloud Phase 2 plan §6.1).
// Every key a live-sync record's cloud part may carry; sync.js drops anything else.
export const CLOUD_FIELDS = ${body};
`);
