// GENERATED by cloud/scripts/cloud-fields.mjs from shared/data/syncRegistry.js.
// Do not edit by hand: change the registry, then regenerate (Cloud Phase 2 plan §6.1).
// Every key a live-sync record's cloud part may carry; sync.js drops anything else.
export const CLOUD_FIELDS = {
  "tables": {
    "dogs": {
      "keys": [
        "breed",
        "breeder_kennel_id",
        "call_name",
        "co_owner_contact_ids",
        "color_markings",
        "created_at",
        "dam_id",
        "date_of_birth",
        "date_of_death",
        "disposition",
        "dob_is_estimated",
        "id",
        "intended_registration",
        "is_archived",
        "kennel_id",
        "litter_id",
        "microchip_id",
        "owner_contact_id",
        "ownership_type",
        "pedigree_only",
        "planned_tests",
        "recorded_coi",
        "registered_name",
        "registration_number",
        "registry",
        "sex",
        "sire_id",
        "status",
        "updated_at",
        "url"
      ],
      "nested": {}
    },
    "events": {
      "keys": [
        "created_at",
        "details",
        "event_date",
        "event_end_date",
        "event_type",
        "id",
        "is_archived",
        "related_contact_id",
        "related_dog_id",
        "reminder_date",
        "reminder_dismissed",
        "subject_id",
        "subject_type",
        "title",
        "updated_at"
      ],
      "nested": {}
    },
    "kennels": {
      "keys": [
        "created_at",
        "id",
        "is_archived",
        "is_own_kennel",
        "kennel_name",
        "location",
        "logo_data_url",
        "preferred_breeds",
        "preferred_test_breeds",
        "preferred_tests",
        "prefix",
        "promote_age_female_months",
        "promote_age_male_months",
        "promote_nudge_enabled",
        "public_id",
        "puppy_record_fields",
        "time_zone",
        "updated_at",
        "waitlist_config",
        "website"
      ],
      "nested": {}
    },
    "contacts": {
      "keys": [
        "contact_type",
        "created_at",
        "id",
        "is_archived",
        "kennel_id",
        "name",
        "updated_at",
        "waitlist_status"
      ],
      "nested": {}
    },
    "pairings": {
      "keys": [
        "created_at",
        "dam_id",
        "expected_due_date",
        "id",
        "is_archived",
        "kennel_id",
        "last_observed_date",
        "method",
        "pairing_type",
        "planned_date",
        "sire_id",
        "status",
        "updated_at"
      ],
      "nested": {}
    },
    "litters": {
      "keys": [
        "accept_deposits_date",
        "created_at",
        "dam_id",
        "estimated_ready_date",
        "foster_direction",
        "foster_partner_contact_id",
        "id",
        "is_archived",
        "kennel_id",
        "litter_registration_number",
        "nickname",
        "pairing_id",
        "picks_opened_date",
        "puppies_born_abnormalities",
        "puppies_born_alive",
        "puppies_born_deceased",
        "puppies_born_total",
        "sire_id",
        "status",
        "updated_at",
        "whelp_date"
      ],
      "nested": {}
    },
    "sales": {
      "keys": [
        "balance_due_date",
        "balance_paid_date",
        "buyer_contact_id",
        "created_at",
        "deposit_date",
        "dog_id",
        "id",
        "is_archived",
        "kennel_id",
        "registration_type",
        "sale_date",
        "status",
        "updated_at"
      ],
      "nested": {}
    },
    "stud_services": {
      "keys": [
        "created_at",
        "direction",
        "fee_structure",
        "id",
        "is_archived",
        "kennel_id",
        "our_dog_id",
        "pairing_id",
        "partner_contact_id",
        "partner_dog_id",
        "pick_status",
        "returned_date",
        "sent_date",
        "status",
        "type",
        "updated_at"
      ],
      "nested": {}
    },
    "contracts": {
      "keys": [
        "contract_type",
        "created_at",
        "id",
        "is_archived",
        "kennel_id",
        "lease_end_date",
        "lease_start_date",
        "related_contact_id",
        "related_dog_id",
        "related_sale_id",
        "related_stud_service_id",
        "signed_date",
        "status",
        "title",
        "updated_at"
      ],
      "nested": {}
    },
    "documents": {
      "keys": [
        "created_at",
        "doc_date",
        "doc_type",
        "dog_id",
        "file_id",
        "id",
        "is_archived",
        "issuer_or_lab",
        "kennel_id",
        "registration_number",
        "registry",
        "result",
        "title",
        "updated_at"
      ],
      "nested": {}
    },
    "files": {
      "keys": [
        "created_at",
        "filename",
        "id",
        "is_archived",
        "mime",
        "sha256",
        "size",
        "thumbnail",
        "updated_at"
      ],
      "nested": {}
    },
    "expenses": {
      "keys": [
        "created_at",
        "id",
        "is_archived",
        "updated_at"
      ],
      "nested": {}
    },
    "breed_feeding_schedules": {
      "keys": [
        "age_columns",
        "breed",
        "created_at",
        "food_brand",
        "id",
        "is_archived",
        "updated_at",
        "weight_rows"
      ],
      "nested": {}
    },
    "accounts": {
      "keys": [
        "account_type",
        "created_at",
        "id",
        "is_archived",
        "name",
        "referral_code",
        "referral_instructions",
        "referral_link",
        "updated_at",
        "website"
      ],
      "nested": {}
    },
    "waitlist_entries": {
      "keys": [
        "application",
        "application_questions",
        "applied_date",
        "approved_date",
        "contact_id",
        "created_at",
        "declined_date",
        "fee_due_date",
        "fee_received_at",
        "fee_received_date",
        "id",
        "is_archived",
        "kennel_id",
        "listen_dam_ids",
        "listen_mode",
        "listen_sire_ids",
        "paused_until",
        "placed_sale_id",
        "position_anchor_date",
        "pref_breed",
        "pref_colors",
        "pref_purposes",
        "pref_sex",
        "ready_timing",
        "removed_date",
        "removed_reason",
        "soon_notified_date",
        "soon_notified_litter_ids",
        "source",
        "status",
        "status_token",
        "updated_at",
        "waitlist_program_id",
        "withdrawn_date"
      ],
      "nested": {
        "application": [
          "email",
          "name"
        ]
      }
    },
    "waitlist_offers": {
      "keys": [
        "chosen_dog_id",
        "counts_as_pass",
        "created_at",
        "eligible_dog_ids",
        "entry_id",
        "id",
        "is_archived",
        "kennel_id",
        "litter_id",
        "offered_date",
        "outcome",
        "outcome_date",
        "picked_date",
        "respond_by_date",
        "sale_id",
        "turn_id",
        "updated_at"
      ],
      "nested": {}
    },
    "waitlist_programs": {
      "keys": [
        "applicable_on_form",
        "created_at",
        "id",
        "is_archived",
        "kennel_id",
        "name",
        "passes_count",
        "pause_allowed",
        "priority",
        "public_description",
        "respond_days_override",
        "updated_at"
      ],
      "nested": {}
    }
  },
  "eventDetails": {
    "acquisition": [
      "source"
    ],
    "vaccination": [
      "lot_number",
      "next_due",
      "vaccine"
    ],
    "preventative": [
      "dose",
      "product"
    ],
    "genetic_test": [
      "lab",
      "panel_name",
      "result"
    ],
    "ofa_pennhip": [
      "joint",
      "method",
      "rating"
    ],
    "breed_specific_test": [
      "result",
      "test_name"
    ],
    "illness": [
      "diagnosis"
    ],
    "medication": [
      "dose",
      "drug",
      "frequency"
    ],
    "surgery": [
      "procedure",
      "vet"
    ],
    "vet_visit": [
      "reason",
      "vet"
    ],
    "injury": [
      "severity"
    ],
    "abnormalities": [
      "type"
    ],
    "weight_check": [
      "time_of_day",
      "weight_lbs",
      "weight_oz"
    ],
    "milestone": [
      "description"
    ],
    "title_earned": [
      "organization",
      "title_abbreviation"
    ],
    "heat_cycle": [],
    "evaluation": [
      "evaluator"
    ],
    "boarding": [
      "boarding_reason",
      "dropoff_time",
      "location",
      "pickup_time"
    ],
    "breeding_tie": [
      "method",
      "tie_date"
    ],
    "progesterone_test": [
      "lab",
      "value"
    ],
    "ultrasound": [
      "confirmed",
      "estimated_count"
    ],
    "pregnancy_update": [],
    "whelping_summary": [
      "live_born",
      "total_born"
    ],
    "placement": [
      "dropoff_method",
      "location",
      "placement_time"
    ],
    "show": [
      "class",
      "club",
      "defeated_champion",
      "entry_status",
      "judge",
      "location",
      "organization",
      "placement",
      "points",
      "points_toward",
      "ring",
      "ring_time",
      "show_name"
    ],
    "note": []
  }
};
